version: '3.8'

services:
  # Node.js application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: video-meet-backend
    ports:
      - "7011:7011"
    environment:
      - BACKEND_PORT=7011
    restart: unless-stopped

networks:
  app-network:
    driver: bridge